apiVersion: operator.kyma-project.io/v1beta1
kind: ModuleTemplate
metadata:
  name: moduletemplate-cluster-ip
  namespace: kcp-system
  labels:
    "operator.kyma-project.io/managed-by": "lifecycle-manager"
    "operator.kyma-project.io/controller-name": "manifest"
    "operator.kyma-project.io/module-name": "cluster-ip"
spec:
  target: control-plane
  channel: beta
  data:
    apiVersion: operator.kyma-project.io/v1alpha1
    kind: ClusterIP
    metadata:
      name: clusterip-nodes
    spec:
      nodeSpreadLabel: kubernetes.io/hostname
  descriptor:
    component:
      componentReferences: []
      name: kyma-project.io/cluster-ip
      provider: internal
      repositoryContexts:
      - baseUrl: ghcr.io/pbochynski/cluster-ip-module
        componentNameMapping: urlPath
        type: ociRegistry
      resources:
      - access:
          digest: sha256:70b0d7ac5080db7a7110c22c04c9796e22b9f807e7b0b2ed07b1bcef58002aa4
          type: localOciBlob
        name: config
        relation: local
        type: yaml
        version: v0.0.14
      - access:
          digest: sha256:82ce60f28c12224e589b3c74c1ff66c5c5438cbed9a482bc4ec40d08ddab4b1d
          type: localOciBlob
        name: cluster-ip
        relation: local
        type: helm-chart
        version: v0.0.14
      sources:
      - access:
          commit: 452f2353d46eac21df1c99e1238e5ef947020ec5
          repoUrl: github.com/kyma-project/cluster-ip
          type: gitHub
        labels:
        - name: git.kyma-project.io/ref
          value: refs/heads/multisvc
          version: v1
        name: module-sources
        type: git
        version: v0.0.14
      version: v0.0.14
    meta:
      schemaVersion: v2
