apiVersion: operator.kyma-project.io/v1alpha1
kind: ClusterIP
metadata:
  labels:
    app.kubernetes.io/name: clusterip
    app.kubernetes.io/instance: clusterip-sample
    app.kubernetes.io/part-of: cluster-ip
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: cluster-ip
  name: clusterip-zones
spec:
  nodeSpreadLabel: kubernetes.io/hostname